
package view;

import enums.TypeUser;
import javax.swing.JOptionPane;
import model.User;


public class viewDashboard extends javax.swing.JFrame {

    /**
     * Creates new form viewDashboard
     */
    
    private User user;
    public viewDashboard(User user) {
        initComponents();
        this.userName.setText(user.getLogin());
        this.user = user;
        this.blockCadastreCategory();
    }

    
    private viewDashboard() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jEditorPane1 = new javax.swing.JEditorPane();
        jMenu1 = new javax.swing.JMenu();
        jPanel1 = new javax.swing.JPanel();
        sidebar = new javax.swing.JPanel();
        avatar = new javax.swing.JLabel();
        userName = new javax.swing.JLabel();
        CadastreNews = new javax.swing.JPanel();
        handleCadastreNews = new javax.swing.JButton();
        avatar_cadastra = new javax.swing.JLabel();
        showNews = new javax.swing.JPanel();
        handleShowNews = new javax.swing.JButton();
        avatar_apresenta = new javax.swing.JLabel();
        cadastreCategory = new javax.swing.JPanel();
        handleCadastreCategory = new javax.swing.JButton();
        avatar_category = new javax.swing.JLabel();
        welcome = new javax.swing.JLabel();
        bccNotices = new javax.swing.JLabel();
        computer = new javax.swing.JLabel();

        jScrollPane1.setViewportView(jEditorPane1);

        jMenu1.setText("jMenu1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(33, 158, 188));

        sidebar.setBackground(new java.awt.Color(255, 255, 255));
        sidebar.setForeground(new java.awt.Color(255, 255, 255));

        avatar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/profile.png"))); // NOI18N

        userName.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        userName.setForeground(new java.awt.Color(33, 158, 188));

        CadastreNews.setBackground(new java.awt.Color(255, 255, 255));
        CadastreNews.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(33, 158, 188)));

        handleCadastreNews.setBackground(new java.awt.Color(255, 255, 255));
        handleCadastreNews.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        handleCadastreNews.setForeground(new java.awt.Color(33, 158, 188));
        handleCadastreNews.setText("Cadastrar noticias");
        handleCadastreNews.setBorder(null);
        handleCadastreNews.setBorderPainted(false);
        handleCadastreNews.setContentAreaFilled(false);
        handleCadastreNews.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        handleCadastreNews.setFocusPainted(false);
        handleCadastreNews.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                handleCadastreNewsMouseClicked(evt);
            }
        });

        avatar_cadastra.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/cadastro.png"))); // NOI18N

        javax.swing.GroupLayout CadastreNewsLayout = new javax.swing.GroupLayout(CadastreNews);
        CadastreNews.setLayout(CadastreNewsLayout);
        CadastreNewsLayout.setHorizontalGroup(
            CadastreNewsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CadastreNewsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(avatar_cadastra)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(handleCadastreNews)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        CadastreNewsLayout.setVerticalGroup(
            CadastreNewsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CadastreNewsLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(CadastreNewsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(avatar_cadastra)
                    .addComponent(handleCadastreNews))
                .addContainerGap())
        );

        showNews.setBackground(new java.awt.Color(255, 255, 255));
        showNews.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(33, 158, 188)));

        handleShowNews.setBackground(new java.awt.Color(255, 255, 255));
        handleShowNews.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        handleShowNews.setForeground(new java.awt.Color(33, 158, 188));
        handleShowNews.setText("Apresentar noticias");
        handleShowNews.setBorder(null);
        handleShowNews.setContentAreaFilled(false);
        handleShowNews.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        handleShowNews.setFocusPainted(false);
        handleShowNews.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                handleShowNewsMouseClicked(evt);
            }
        });
        handleShowNews.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                handleShowNewsActionPerformed(evt);
            }
        });

        avatar_apresenta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/apresentador.png"))); // NOI18N

        javax.swing.GroupLayout showNewsLayout = new javax.swing.GroupLayout(showNews);
        showNews.setLayout(showNewsLayout);
        showNewsLayout.setHorizontalGroup(
            showNewsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, showNewsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(avatar_apresenta)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(handleShowNews)
                .addContainerGap(22, Short.MAX_VALUE))
        );
        showNewsLayout.setVerticalGroup(
            showNewsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(showNewsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(showNewsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(avatar_apresenta)
                    .addComponent(handleShowNews))
                .addContainerGap(7, Short.MAX_VALUE))
        );

        cadastreCategory.setBackground(new java.awt.Color(255, 255, 255));
        cadastreCategory.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(33, 158, 188)));

        handleCadastreCategory.setBackground(new java.awt.Color(255, 255, 255));
        handleCadastreCategory.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        handleCadastreCategory.setForeground(new java.awt.Color(33, 158, 188));
        handleCadastreCategory.setText("Cadastrar categoria");
        handleCadastreCategory.setBorder(null);
        handleCadastreCategory.setBorderPainted(false);
        handleCadastreCategory.setContentAreaFilled(false);
        handleCadastreCategory.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        handleCadastreCategory.setFocusPainted(false);
        handleCadastreCategory.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                handleCadastreCategoryMouseClicked(evt);
            }
        });
        handleCadastreCategory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                handleCadastreCategoryActionPerformed(evt);
            }
        });

        avatar_category.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/cadastro.png"))); // NOI18N

        javax.swing.GroupLayout cadastreCategoryLayout = new javax.swing.GroupLayout(cadastreCategory);
        cadastreCategory.setLayout(cadastreCategoryLayout);
        cadastreCategoryLayout.setHorizontalGroup(
            cadastreCategoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cadastreCategoryLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(avatar_category)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(handleCadastreCategory)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        cadastreCategoryLayout.setVerticalGroup(
            cadastreCategoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cadastreCategoryLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(cadastreCategoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(avatar_category)
                    .addComponent(handleCadastreCategory))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout sidebarLayout = new javax.swing.GroupLayout(sidebar);
        sidebar.setLayout(sidebarLayout);
        sidebarLayout.setHorizontalGroup(
            sidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sidebarLayout.createSequentialGroup()
                .addGroup(sidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(sidebarLayout.createSequentialGroup()
                        .addGap(68, 68, 68)
                        .addComponent(avatar))
                    .addGroup(sidebarLayout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addComponent(userName)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(showNews, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(CadastreNews, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(cadastreCategory, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        sidebarLayout.setVerticalGroup(
            sidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sidebarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(avatar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(userName)
                .addGap(39, 39, 39)
                .addComponent(CadastreNews, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(showNews, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cadastreCategory, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        welcome.setBackground(new java.awt.Color(255, 255, 255));
        welcome.setFont(new java.awt.Font("SansSerif", 1, 36)); // NOI18N
        welcome.setForeground(new java.awt.Color(255, 255, 255));
        welcome.setText("Seja bem vindo ao ");

        bccNotices.setFont(new java.awt.Font("SansSerif", 1, 36)); // NOI18N
        bccNotices.setForeground(new java.awt.Color(255, 255, 255));
        bccNotices.setText("BCC noticias");

        computer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/responsive.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(sidebar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 80, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(welcome)
                        .addGap(78, 78, 78))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(computer)
                            .addComponent(bccNotices))
                        .addGap(147, 147, 147))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(sidebar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addComponent(welcome)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bccNotices)
                .addGap(38, 38, 38)
                .addComponent(computer)
                .addContainerGap(79, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void handleShowNewsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_handleShowNewsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_handleShowNewsActionPerformed

    private void handleCadastreCategoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_handleCadastreCategoryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_handleCadastreCategoryActionPerformed

    private void handleCadastreCategoryMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_handleCadastreCategoryMouseClicked
        viewCadastreCategory cadastreCategory = new viewCadastreCategory(this, true);
        cadastreCategory.setVisible(true);
    }//GEN-LAST:event_handleCadastreCategoryMouseClicked

    private void handleCadastreNewsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_handleCadastreNewsMouseClicked
        viewPainelNews viPainelNews = new viewPainelNews();
        viPainelNews.setVisible(true);
    }//GEN-LAST:event_handleCadastreNewsMouseClicked

    private void handleShowNewsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_handleShowNewsMouseClicked
        viewListNews listNews = new viewListNews(null, true);
        listNews.setVisible(true);
    }//GEN-LAST:event_handleShowNewsMouseClicked
    
    
    private Boolean verifyTypeUser(User user){
        if(user.getType().equals(TypeUser.Comum)) return true;
        
        else
            return false;
    }
    
    private void blockCadastreCategory(){
        if(verifyTypeUser(user)){
            cadastreCategory.setVisible(false);
            handleCadastreCategory.setVisible(false);
            avatar_category.setVisible(false);
        }
    }
   
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(viewDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(viewDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(viewDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(viewDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new viewDashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel CadastreNews;
    private javax.swing.JLabel avatar;
    private javax.swing.JLabel avatar_apresenta;
    private javax.swing.JLabel avatar_cadastra;
    private javax.swing.JLabel avatar_category;
    private javax.swing.JLabel bccNotices;
    private javax.swing.JPanel cadastreCategory;
    private javax.swing.JLabel computer;
    private javax.swing.JButton handleCadastreCategory;
    private javax.swing.JButton handleCadastreNews;
    private javax.swing.JButton handleShowNews;
    private javax.swing.JEditorPane jEditorPane1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel showNews;
    private javax.swing.JPanel sidebar;
    private javax.swing.JLabel userName;
    private javax.swing.JLabel welcome;
    // End of variables declaration//GEN-END:variables
}
